platform :ios, ‘8.0’

target 'Custom' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Custom

    pod 'SDWebImage'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'FMDB'
    pod 'SVProgressHUD'
    pod 'SDCycleScrollView'
    pod 'MJRefresh'
    pod 'YYModel'
    pod 'TPKeyboardAvoiding'
    pod 'MBProgressHUD'
    pod 'MJExtension'

end
